name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: ls -l
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 14
          check-latest: true
      - run: npm install -g bats
      - run: bats -v
      - run: ls -l
